name: pushworld_cscg_torch
channels:
  - conda-forge
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - asttokens=3.0.0
  - blas=2.132
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cpython=3.10.18
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - farama-notifications=0.0.4
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - fsspec=2025.7.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gymnasium=1.0.0
  - h2=4.2.0
  - harfbuzz=11.3.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2024.2.1
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.8
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libsqlite=3.50.3
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.51.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - mkl-devel=2024.2.2
  - mkl-include=2024.2.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numba=0.61.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycairo=1.28.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-igraph=0.11.9
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pywin32=311
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qhull=2020.2
  - qt6-main=6.9.1
  - requests=2.32.4
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.8
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.13.0
  - texttable=1.7.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
prefix: C:\Users\jacob\miniforge3\envs\pushworld_cscg_torch
