summary: "Debug new training procedure"

puzzle: "manual/corridor6x1"
n_obs: 6
encoder: "SimpleCNN"
clones_per_obs: 1
seq_len: 300

training_procedure:
  n_cycles: 5
  n_iters_cscg: 100
  n_iters_encoder: 3
  encoder_batch_size: 128
  entropy_weight: 0

environment_reset:
  method: "gaussian"
  mean: 6
  variance: 0

wandb:
  project: "cscg-pushworld"
  entity: "jacob-simon"
