summary: "Debug new training procedure"

puzzle: "manual/box"
n_obs: 4
encoder: "SimpleCNN"
clones_per_obs: 1
seq_len: 100
training_procedure:
  n_cycles: 5
  n_iters_cscg: 100
  n_iters_encoder: 5

environment_reset:
  method: "gaussian"
  mean: 6
  variance: 0